### PR TITLE
Add docker healthcheck

### PR DESCRIPTION
**Pull request by JonZeolla**
This depends on #347

### CODE REVIEW

**Comment by jhpyle** [comment]
When HTTPS is used, nginx returns a 301 for that URL, which is not a `--fail`.  nginx will return a 301 once nginx starts, even if uwsgi fails to start.  Following the 301 leads to a certificate error if HTTPS is used.

I am not sure it is a good idea to exit just because the web app doesn't come online.  When I have startup problems I `docker exec` into the container so that I can interactively figure out what is wrong.  Some configurations should become live in 90 seconds, while others might need 20 minutes to download data from the cloud.

In the Kubernetes implementation I have a "monitor" container that serves up status information, as well as containers that wait for other containers' health checks to become good. So I understand the value of health checks, but they are pretty complex to implement.

**Comment by JonZeolla** [comment]
Yes this is for a k8s deployment.  Optimally, a [variety of probes](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/) should be used to properly identify the running container status and you should never need to exec into a running cluster.

Previously I was checking services were running, which is another option, but as discussed in slack the current design there doesn't give a single point to monitor.

My goal is to improve the project's k8s deployment story instead of forking and improving on my own.  Happy to talk through this more here or in slack.

**Comment by JonZeolla** [comment]
I was also considering a refactor to a multi stage Dockerfile to make it easier to leave out components like the postgres db, or just have a dockerfile for each service as an alternative to the all in one, which would be the best direction for a k8s native deployment (and what I plan to do, just haven't decided if that's a PR or external project yet; open to thoughts)

**Comment by drewfreyling** [comment]
@JonZeolla i'm also agreeing that making the stack work better for k8s is a great idea. I'd rather not fork it either.

**Pull request closed without merging**
