### PR TITLE
Combined logic for showifdef, value, and defined

### PR DESCRIPTION
**Pull request by BryceStevenWilley**
Two changes:
* `showifdef`, `value`, and `defined` all used the `components_of` function. However, the `components_of` function doesn't handle complex nesting, just returning wrong values for some question (for example, using one variable as an index into another variable). This PR fixes that bug, and also adds support for binary operations in expressions, which is useful for `showifdef` or `value`.
* to implement the above, I combined the code for `showifdef`, `value`, and `defined`, which all have an identical function body, just with different return behaviors (`value` specifically just calls `force_ask` each time the other functions return). This change should make things a bit simpler, It also should save a small bit of compute for lots of showifs in a row that are all defined, since previously that function was repeating the same calculations twice

Open to any discussion of this, and can change things around if wanted.

Tested on the below interview, which can't be run on the current main because of a bug in value, but if you comment out `vals`, you can see the wrong results being shown on the current main.
```yaml
code: |
  a = {'hi': [1, 2, 4, 0], 'bye': {'a': 1, 'b': 2}}
  b = 'hi'
  one = 1
---
code: |
  c = 'bye'
---
code: |
  d = 'b'
---
code: |
  two = 2
---
code: | 
  a
  strs = ['a["hi"]', 'a[b]', 'a[b][a["bye"]["a"]]', 'a[b][one + 1]', 'a[b][1 + two]', 'a[c]', 'a[c][d]']
---
code: |
  defineds = [defined(st) for st in strs]
---
code: |
  showifdefs = [showifdef(st) for st in strs]
---
code: |
  showifdefs2 = [showifdef(st, 'Not there') for st in strs]
---
code: |
  vals = [value(st) for st in strs]
---
mandatory: True
question: |
  Test
subquestion: |
  ${ strs }
  
  ${ defineds }
  
  ${ showifdefs }
  
  ${ showifdefs2 }
  
  ${ vals }
```

### CODE REVIEW

**Comment by jhpyle** [comment]
Why was it necessary to add the `BinOp` thing?

**Comment by BryceStevenWilley** [comment]
Because without `BinOp` method, the AST visitor ignores the binary operators, but still visits name nodes on either side. So if you had something like `value("a + b")`, without BinOp it would just return just the value of 'b', without any sort of error or indication that it doesn't handle binary ops correctly. I considered trying to just add an exception / error when binary ops are used, but it's about as much code to do that, and it's not consistent with the behavior of `value("1 + 2")`, which gets directly evaluated and just works.

**Comment by jhpyle** [comment]
I would just say that writing `value("a + b")` is illegal and if you write stuff like that you will get unexpected results. `value()`, `defined()`, etc. are only supposed to be used with a single variable, and `a + b` is not a single variable, it's a math formula. A single variable might contain a BinOp, though. E.g., `'foo["" + asdf].bar[1+ii]'` where `foo` is a `DADict` and `foo[i].bar` is a `DAList`.

Maybe this could be upgraded to some kind of recursive thing that handles arbitrary expressions as well as single variables, but I haven't gotten that far.

Anyway, I commented out your BinOp stuff because it caused incorrect results with valid single-variable input like `foo["bar"].bar[0+ii]`.

**Comment by jhpyle** [comment]
I added the last five lines to this function, which I think will ensure that exceptions get triggered in the right order. E.g., if everything is undefined, `foo` should be sought before `ii`.
```
def components_of(full_variable):
    node = ast.parse(full_variable, mode='eval')
    crawler = lister()
    crawler.visit(node)
    components = list(reversed(crawler.stack))
    start_index = 0
    for the_index, elem in enumerate(components):
        if elem[0] == 'name':
            start_index = the_index
    return components[start_index:]
```

**Comment by BryceStevenWilley** [comment]
The reasoning for limiting BinOp scope makes sense. Exception / sought order wasn't a thing I had considered, so thanks for that fix as well. I agree your patch should be correct. I'll consider the BinOp stuff a bit more and make a another PR at some point.

**Pull request merged**
