### PR TITLE
expose transform_json_vars

### PR DESCRIPTION
**Pull request by BryceStevenWilley**
This PR does two small changes to some core functions.

1) It exposes the `transform_json_varirables` function of `server` as just a global function, similar to other one line functions in `functions.py` that delegate to the `server` object.
2) It officially adds the `transform_json_variables` and `serializable_dict` functions to `util.py`, making them directly callable from interviews.

1 does add specific capabilities to interviews, since before, transforming variables was only done in other functions that also saved the session or got every single variable, instead of just the one you need.

2 isn't strictly necessary, but I recently came across a situation that highly needs it, and IMO makes it easier to write maintainable DA code. Essentially, I needed a background task to be "callable" from the same interview with different parameters, some of which need to be user provided. Since it's not entirely programmatic, I decided to put all of the related variables to starting the background task inside of a special generic object, including the `background_action`. The background action then occurs, and the results (a simple DAList with some DA objects with custom attributes, nothing that isn't pickelable or serializable) are returned through `get` (we cannot use `background_action_response` because it's event doesn't work with a generic object). However, an undocumented restriction on what `background_action` returns is that it needs to be json serializable (specifically calling the `jsonify` function in flask, which `server.py:jsonify_with_cache` does. Only python primitives and objects like list and dict work). Exposing `transform_json_variables` and `serializable_dict` help you serialize and deserialize your DAObjects so you can properly use `background_action`.

Again, 2 is optional, since you could use your own module files, but I do think that those two functions should be added to the "public" DA API, since they're required to use `background_action` in an encapsulated way.

### CODE REVIEW

**Comment by jhpyle** [comment]
When you talk about "what `background_action()` returns," are you talking about what that function literally returns, or are you talking about you get when the background action finishes and you call `.get()` in order to obtain the thing that the background task passed back to the interview using `background_response()`?

What `background_action()` literally returns is an object that holds as an attribute a Celery `AsyncResult`, which is what is returned from calling `.delay()` on `docassemble.webapp.worker.background_action`. The Celery `ASyncResult` does not contain the result of the background task itself; it is just an object with methods for retrieving the result from the Celery server (Celery uses Redis and RabbitMQ). I use a wrapper class `MyAsyncResult` that caches the return value in the `_cached_result` attribute. One of the rules about Celery is that you can't call Celery from Celery. A background task cannot spawn a background task, for example. If you are passing an `ASyncResult` from the interview context to a Celery worker, that might trigger a weird Celery error. I don't know if that is the problem you are experiencing or not, but it might explain whatever problem you are seeing.

If by "what `background_action()` returns" you mean what `.get()` returns, then I am getting different results from you, because I have no problem passing pickleable but non-JSON-serializable objects from the interview to the background task and from the background task to the interview. For example, I can pass `enumerate` objects back and forth. It is possible to configure Celery so that JSON is used as the result serializer, and if your Celery was configured that way, then I could see how you would think there was a JSON serialization requirement. But that is not how I have configured Celery (see `docassemble.webapp.config_worker`). Celery might have some type of failure condition where if the pickle-based result serializer can't be enabled, it falls back to using JSON as the result serializer. That might happen if there is a RabbitMQ failure.

**Comment by BryceStevenWilley** [comment]
> When you talk about "what background_action() returns," are you talking about what that function literally returns, or are you talking about you get when the background action finishes and you call .get()?

I'm talking about the latter, sorry for the confusion. However, I'm now having trouble reproducing my issue. Below is the logged error that happened when I first ran into the problem, and it was causing an error in the interview as well. However, the error doesn't seem to happen in the interview anymore, though this same error is present in the logs.

```
File "/usr/share/docassemble/local3.8/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request     rv = self.dispatch_request()   
File "/usr/share/docassemble/local3.8/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request     return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)   
File "/usr/share/docassemble/local3.8/lib/python3.8/site-packages/docassemble/webapp/server.py", line 5902, in checkin     return jsonify_with_cache(success=True, chat_status=chatstatus, num_peers=num_peers, help_available=help_available, phone=call_forwarding_message, observerControl=observer_control, commands=commands, checkin_code=checkin_code)   
File "/usr/share/docassemble/local3.8/lib/python3.8/site-packages/docassemble/webapp/server.py", line 5627, in jsonify_with_cache     response = jsonify(*pargs, **kwargs)   
File "/usr/share/docassemble/local3.8/lib/python3.8/site-packages/flask/json/__init__.py", line 297, in jsonify     f"{dumps(data, indent=indent, separators=separators)}\n",   
File "/usr/share/docassemble/local3.8/lib/python3.8/site-packages/flask/json/__init__.py", line 131, in dumps     return _json.dumps(obj, **kwargs)   
File "/usr/lib/python3.8/json/__init__.py", line 234, in dumps     return cls(   File "/usr/lib/python3.8/json/encoder.py", line 201, in encode     chunks = list(chunks)   
File "/usr/lib/python3.8/json/encoder.py", line 431, in _iterencode     yield from _iterencode_dict(o, _current_indent_level)   
File "/usr/lib/python3.8/json/encoder.py", line 405, in _iterencode_dict     yield from chunks   
File "/usr/lib/python3.8/json/encoder.py", line 325, in _iterencode_list     yield from chunks   
File "/usr/lib/python3.8/json/encoder.py", line 405, in _iterencode_dict     yield from chunks   
File "/usr/lib/python3.8/json/encoder.py", line 325, in _iterencode_list     yield from chunks   
File "/usr/lib/python3.8/json/encoder.py", line 438, in _iterencode     o = _default(o)   
File "/usr/share/docassemble/local3.8/lib/python3.8/site-packages/flask/json/__init__.py", line 50, in default     return super().default(o)   
File "/usr/lib/python3.8/json/encoder.py", line 179, in default     raise TypeError(f'Object of type {o.__class__.__name__} ' 
TypeError: Object of type DAList is not JSON serializable 
```
I'm not sure how this caused an interview error, or even really what it's doing, but I just don't want to to break the interview somehow.

**Comment by jhpyle** [comment]
Ok, I think you are calling `background_action` with a second positional parameter, which instructs docassemble to pass the result of the background action to the browser. In that case, the thing that is returned from the background task would need to be JSON serializable because the browser only speaks JavaScript, not Python.

**Comment by BryceStevenWilley** [comment]
I see. You're right, I was using `background_action('my_task', 'refresh', ...), and I didn't realize that `refresh` also passes the result to the browser. Thanks for the help, apologies for the superfluous PR.

**Comment by jhpyle** [comment]
Sorry about that -- the `refresh` command shouldn't pass the result to the browser. I'll fix that in the next version. I often return complex objects from background tasks but I guess I never tried that in combination with the `refresh` option before.

**Pull request closed without merging**
