### PR TITLE
Mix-mode syntax highligher for python in yaml for codemirror. Fixes #259

### LINKED ISSUE #259: Build a mixed-mode syntax highlighter for CodeMirror, mixing YAML and Python modes
This is a "help wanted" issue that does not require any knowledge of docassemble itself; it is a JavaScript issue.

Docassemble uses CodeMirror's YAML mode for providing users with a web interface for editing YAML interview files.  Docassemble lets you write Python code inside YAML text blocks.  Any time this happens:
```
code: |
  number_of_children = len(client.child)
```
the text inside `code` is assumed to be Python code.  Sometimes `code` blocks are nested, sometimes they aren't.

It would be helpful to have syntax highlighter that treats the file as YAML but treats `code` text as Python.  An example of mixed-mode CodeMirror syntax highlighting is here:
https://github.com/codemirror/CodeMirror/blob/master/mode/htmlmixed/htmlmixed.js

### PR DESCRIPTION
**Pull request by plocket**
Unfortunately untested. It should at least be close.

### CODE REVIEW

**Comment by jhpyle** [comment]
I tried to test it with the attached test environment but the ending regexp didn't seem to work; Python mode turned on but YAML mode stopped working afterward.

[yamlmixed.zip](https://github.com/jhpyle/docassemble/files/4176324/yamlmixed.zip)

**Comment by plocket** [comment]
Try this. It may not have liked testing multiple lines.

**Comment by jhpyle** [comment]
If you unpack the above zip file, make that regexp change to yaml-mixed-highlighter.yml, and open testcodemirror.html using File -> Open File in your web browser, you can see that it doesn't handle indented `code` blocks.  Also it doesn't colorize `code` according to YAML rules.

**Comment by plocket** [comment]
Hmm, it seems that I didn't understand the problem statement correctly. I'll see what I can do.

**Comment by plocket** [comment]
These specs will take a lot more research to implement. I'll PR again if I get there.

**Pull request closed without merging**
