### PR TITLE
Markdown to docx RichText converter

### PR DESCRIPTION
**Pull request by epompeii**
This commit adds a function that takes in a dictionary of jinja2 tags
that are associated with Markdown objects. It converts a Markdown
object it to HTML using markdown, then it parses the HTML with
BeautifulSoup and adds RichText to a docx template using docxtpl's
DocxTemplate, based on the Jinja2 tags.

The function then returns the filled DocxTemplate.

### CODE REVIEW

**Comment by jhpyle** [comment]
Very cool!  I'll check it out.

**Comment by jhpyle** [comment]
The order in which Beautiful Soup parses the HTML seems to be outer-in rather then left-to-right through the tokens.  So when I give it Markdown like the following, some of the text content gets repeated.  E.g., a `p` element reduced to text becomes "This is italic text" but then later the `em` element is reduced to the text "italic text," so the phrase "italic text" appears twice.  Did you get this also in your testing?

```
  This is *italic text*.
  This is **bold text**.
  This is __also bold text__.

  > This is some block-quoted
  > text

  ### This is a heading

  This is some regular text.

  Here is a bullet list:

  * Apple
  * Peach
  * Pear

  Here is a numbered list:

  1. Nutmeg
  2. Celery
  3. Oregano

  Your favorite fruit is ${ favorite_fruit }.
  
  Here is a
  [link to a web site](https://google.com).
```
See [the_file.pdf](https://github.com/jhpyle/docassemble/files/2308548/the_file.pdf) for the PDF I get.

Maybe the thing to do is to bypass the RichText/"run" concept and go right to the XML (which is what a RichText object yields anyway).  E.g., look at the code of the docx `add()` method for reference and use BeautifulSoup to edit the HTML in place, turning the HTML tags into Word XML tags.

**Comment by jhpyle** [comment]
Actually, I take that back -- the docx XML is not nested the way HTML is.  A paragraph in docx XML is a sequence of "runs" of the same character style, without any nesting.  So converting HTML to XML would require traversing the tree, keeping track of your depth, and inserting closing tags before opening tags.

**Comment by epompeii** [comment]
Great catch!
I remember thinking about that being an issue, but I somehow missed it in testing.
Given the structural differences between HTML and docx XML, I am working towards recursively decomposing the XML into a linear output. From there I can just look at its tag hierarchy and assign it the necessary formatting, using RTF.

**Pull request merged**
